using System;

namespace OotReference
{
    public enum Location : int
    {
        LonLonRanch = 5,
        HyruleField = 2,
        HyruleCastle = 3,
        HyruleTown = 4,
        KokiriForest = 0,
        DekuTree = 5,
        LostWoods = 1,
        ZorasFountain,
        ZorasDomain,
        ZorasRiver,
        GerudoValley,
        GerudoFortress,
        Wasteland,
        DesertColossus,
        GerudoTrainingGrounds,
        LakeHylia,
        FishingPond,
        LakeHyliaLab,
        DeathMountainTrail,
        DeathMountain,
        KakarikoVillage,
        GoronCity,
        DodongoCavern,
        JabuJabu,
        ForestTemple,
        WaterTemple,
        ShadowTemple,
        SpiritTemple,
        TempleOfTime,
        FireTemple,
        Grotto,
        Graveyard,
        SacredForestMedow,
        FaerieFountain,
        GhanonsCastle,
        GhanonsTower,
        CastleEscape,
        KakarikoArchery,
        BottomOfTheWell,
        HouseOfSkulltulas,
        Windmill
    }
    public enum Trick
    {
        BombHover,
        VoidWarp,
        WrongWarp,
        LedgeClip,
        InfiniteSwordGlitch,
        OcarinaDive,
        KukoDive,
        SuperSwim,
        OcarinaItems,
        SuperSlide,
        HyperESS,
        ForwardESS,
        ExtendedSuperSlide,
        EquipSwap,
        BottleDuping,
        ReverseBottleAdventure,
        BottleAdventure,
        MasterGlitch,
        PowerCrouchStab,
        ZSlide,
        MidoSkip,
        Gainer,
        BigStickEnergy,
        ArcheryGerudoChest,
        ActorDuping,
        RecoilFlip, // hinted
        MegaSideHop,
        BackWalking,
        Storage,
        MegaFlip, // hinted
        ExitForestEarly,
        StaleReferenceManipulation,
        NoBoots,
        WeirdShot,
        BoatSkip,
        NaviDive,
        ReverseWaterTemple,
        ActionSwap,
        DoorOfTimeSkip,
        ItemOnB,
	    WaterExtendedSuperSlide,
        LedgeCancel,
        HookshotJump,
        BridgeOffCamera,
        // there are more
        EponaPush, // mm only? hinted
        QuickPutAway,
        BottleDupe,
	    GhanonFloor,
        GetItemManipulation,
        DoorClip,
        InactiveNpcPush,
        DoomJump,
        CutsceneFix,
        PauseBuffer,
        StatueClimb,
        LightNodeSRM,
        EntrancePointGlitch,
        DownA,
        FlexDrop, //-- high enough other ammo, hearts, magic to get other types of ammo,
        BlankA,
		SkullPush,
		HorsePush,
		OneSixteenth,
		HeapWarp,
		HeapManipulation,
		ZeroSpeed,
		TimeStop,
		Hoverbootsed,
		MegaEeno,
		DinoplVoidWarp,
		// continued from 2-21
		ZoraWaterSeam,
		Spin2Win,
		FireUppies,
		AntiGravity,
		PoeDive,
		BugsDotSkip,
		LedgeCancel,
		ZombieJump,
		Backshot,
		FaroresWindButtonPressDotSkip,
		DeathHole,
		LacsWrongWarp,
		AntiGravity,
		ZombieWalkWESS,
		TempB
    }
    public enum Item
    {
        KokiriOcarina,
        OcarinaOfTime,
        Hoodshot,
        Longshot,
        Boomerang,
        Slingshot,
        Bottle,
        RedPotion,
        BluePotion,
        GreenPotion,
        Bomb,
        Bomchu,
        Faerie,
        Bugs,
        Water,
        Fish,
        MagicBeans,
        KokiriSword,
        BiggoronSword,
        MasterSword,
        HoverBoots,
        IronBoots,
        NormalBoots,
        GoronTunic,
        GreenTunic,
        ZoraTunic,
        HylianShield,
        MirrorShield,
        DekuNuts,
        DekuStick,
        FireArrows,
        LightArrows,
        IceArrows,
        NayrusLove,
        DinsFire,
        FaroresWind,
        TradeQuestItem,
        MaskItem,
        DekuShield,
        GreenRupee,
        BlueRupee,
        RedRupee,
        BigRupee,
        SilverRupee,
        YellowRupee,
        Rupees,
        HeartPiece,
        HeartContainer,
        GoldSkultula,
        ZeldasLetter,
        RuttosBottle,
        KeatonMask,
        KukoEgg,
        BombBag,
        SlingshotBagUpgrade,
        FaerieBow,
        QuiverUpgrade,
        SlingshotSeeds,
        WalletUpgrade,
        StoneOfAgony,
        // maybe there are more
        Milk
    }
    public enum ForestEscape
    {
        NutEscape,
        WessEscape,
        IsgEscape,
        LedgeClip,
        NaviDive,
        RockEscape
    }
    public enum Song
    {
        BoleroOfFire,
        ZeldasLulaby,
        SariasSong,
        SongOfTime,
        SunSong,
        EponasSong,
        ScarecrowsSong,
        SerenadeOfWater,
        // forgetting the rest
        ShadowSong,
        SpiritSong,
        ForestSong,
        TempleOfTimeSong,
        SongOfStorms
    }
}
